import React from "react";
import {Center, Box, Button} from '@chakra-ui/react'

export const EquipmentScreen = () => {

    return (
			<Center height="100%">
				<Box pos="relative" width="100%" height="100%">
					<Button
						position="absolute"
						top="5%"
						left="44%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Head
					</Button>
					<Button
						position="absolute"
						top="20%"
						left="44%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Necklace
					</Button>
					<Button
						position="absolute"
						top="35%"
						left="44%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Chest
					</Button>
					<Button
						position="absolute"
						top="50%"
						left="44%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						legs
					</Button>
					<Button
						position="absolute"
						top="65%"
						left="44%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Boots
					</Button>
					<Button
						position="absolute"
						top="20%"
						left="20%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Cape
					</Button>
					<Button
						position="absolute"
						top="20%"
						left="66%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Quiver
					</Button>
					<Button
						position="absolute"
						top="35%"
						left="20%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Weapon
					</Button>
					<Button
						position="absolute"
						top="35%"
						left="66%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Shield
					</Button>
					<Button
						position="absolute"
						top="50%"
						left="20%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Gloves
					</Button>
					<Button
						position="absolute"
						top="50%"
						left="66%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Ring
					</Button>
					<Button
						position="absolute"
						top="80%"
						left="20%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Pickaxe
					</Button>
					<Button
						position="absolute"
						top="80%"
						left="44%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Hatchet
					</Button>
					<Button
						position="absolute"
						top="80%"
						left="66%"
						width="4rem"
						height="4rem"
						backgroundColor="#3b414c"
					>
						Hammer
					</Button>
				</Box>
			</Center>
		)
}